version: "3.3"

services:
  traefik:
    image: traefik:2.6
    ports:
      # Define our ports as host mode to make available the user's ip
      - target: 443
        published: 443
        mode: host
      - target: 80
        published: 80
        mode: host
    networks:
      - web
    volumes:
      # Link Traefik to the docker socket, that enable auto detection of Traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../configs/traefik/static/traefik.yml:/etc/traefik/traefik.yml:ro
    deploy:
      # Make Traefik works as replicated with needed, by default one
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 15s
      restart_policy:
        condition: on-failure
      labels:
        # Define our traefik needed values
        - "traefik.docker.network=web"
        - "traefik.http.services.traefik.loadbalancer.server.port=80"

networks:
  web:
    external:
      name: web
