version: "3.3"

services:
  mysql:
    image: mysql:8
    volumes:
      # Store mysql data
      - type: bind
        source: ../../vols/mysql
        target: /var/lib/mysql
      
    networks:
      - local
    # Stay as swarm, however it should'nt be replicated
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [ node.role == manager ]
      labels:
        # Disable traefik on this container
        - "traefik.enable=false"
    environment:
      # Use docker secret to store and share password through the network
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root
    secrets:
      - mysql-root

networks:
  local:
    external:
      name: local

secrets:
  mysql-root:
    external: true
